#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

if [[ "$new_path" != "/" ]]; then
	ynh_die --message="SeerrNG does not support URL subpaths. Choose the root of a dedicated domain."
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping SeerrNG..."
ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating SeerrNG's Nginx domain configuration..."
ynh_config_change_url_nginx

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting SeerrNG..."
ynh_systemctl --service="$app" --action="start" \
	--wait_until="Server ready on" \
	--log_path="$data_dir/logs/seerr.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Change of URL completed for $app"
