#!/bin/bash

source _common.sh

ynh_script_progression "Installing SeerrNG release files..."
ynh_setup_source --dest_dir="$install_dir"
chown -R "$app:$app" "$install_dir"

ynh_script_progression "Preparing persistent settings and proxy-aware client IP handling..."
seerrng_seed_settings

ynh_script_progression "Configuring the Nginx reverse proxy and systemd service..."
seerrng_prepare_service

ynh_script_progression "Starting SeerrNG..."
ynh_systemctl --service="$app" --action="start" \
	--line_match="Server ready on" \
	--log_path="$data_dir/logs/seerr.log"
seerrng_register_service

ynh_script_progression "SeerrNG installation completed"
