#!/bin/bash

source _common.sh

ynh_script_progression "Stopping SeerrNG..."
ynh_systemctl --service="$app" --action="stop"

ynh_script_progression "Installing the pinned SeerrNG release..."
ynh_setup_source --dest_dir="$install_dir" --full_replace=1
chown -R "$app:$app" "$install_dir"

ynh_script_progression "Preserving persistent settings and refreshing proxy configuration..."
seerrng_seed_settings
seerrng_prepare_service

ynh_script_progression "Starting SeerrNG..."
ynh_systemctl --service="$app" --action="start" \
	--line_match="Server ready on" \
	--log_path="$data_dir/logs/seerr.log"
seerrng_register_service

ynh_script_progression "SeerrNG upgrade completed"
